### PR TITLE
Use abc for abstract class

### PR DESCRIPTION
**Pull request by suzaku**

### CODE REVIEW

**Comment by ojii** [comment]
I had no clue you could do that. Will have to have a closer look at this, but thank you for your pull request!

**Comment by suzaku** [comment]
@ojii It's available for Python2.6+. http://docs.python.org/2/library/abc.html

**Comment by chrisglass** [comment]
Out of curiosity, what exactly does this bring over using plain old python objects as an abstract base class? I had no clue this existed - thanks for sharing!

**Comment by ojii** [comment]
@chrisglass the advantages is that you can't instantiate the ABC class or any subclass of it that does not define all `abstractmethod`s and `abstractproperty`s. This might sound like a drawback at first, but it's actually quite handy to enforce a certain API.

**Comment by chrisglass** [comment]
Ah gotcha - sounds great!

Thanks for pointing this out, I might use that elsewhere :+1:

**Pull request closed without merging**
